CREATE TABLE books (
   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   title varchar(40) NOT NULL,
   subtitle text NOT NULL,
   summary text NOT NULL,
   content text NOT NULL,
   authorname varchar(40) NOT NULL,
   coauthor text,
   audible text,
   paperback text,
   kindle text,
   ebook text,
   image text,
   tag varchar(40)
);

INSERT INTO books (title, subtitle, summary, content, authorname, coauthor, audible, paperback, kindle, ebook, image, tag) VALUES   
(
   'The Kubernetes Book',
   'The ultimate book on Kubernetes!',
   'Deep on the theory and packed with optional hands-on examples. This book will help you master Kubernetes.',
   'You’ll learn: Kubernetes architecture, how to build Kubernetes, deploy an app, self-heal it, scale it up and down, perform rolling updates, learn how to secure Kubernetes and much, much more….',
   'Nigel Poulton',
   NULL,
   'https://www.amazon.com/The-Kubernetes-Book-Nigel-Poulton-audiobook/dp/B07Q8QH7DL/ref=tmm_aud_swatch_0?_encoding=UTF8&qid=1671102329&sr=1-3',
   'https://www.amazon.com/Kubernetes-Book-Nigel-Poulton/dp/B09QFM8H6T/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1671102329&sr=1-3',
   'https://www.amazon.com/Kubernetes-Book-Version-November-2018-ebook/dp/B072TS9ZQZ/ref=sr_1_1?crid=1C2R5Y8GC3CQS&keywords=Kubernetes+book+kindle&qid=1675352602&sprefix=kubernetes+book+kindle%2Caps%2C201&sr=8-1',
   'https://leanpub.com/thekubernetesbook',
   'https://i0.wp.com/nigelpoulton.com/wp-content/uploads/2023/01/TKB_3D_2023.png?resize=315%2C371&amp;ssl=1',
   ''
),
(
   'Docker Deep Dive',
   'Docker Deep Dive is a “masterpiece”, the “gold-standard”, and the perfect book for learning Docker.',
   'This book also provides a solid foundation for advancing to Kubernetes and other technologies such as cloud-native WebAssemly (Wasm).',
   'Rated by BookAuthority (as seen on CNN and Forbes) in 2020 as “the number 1 all-time best book on Docker”.',
   'Nigel Poulton',
   NULL,
   NULL,
   'https://www.amazon.com/Docker-Deep-Dive-Nigel-Poulton/dp/1521822808/ref=sr_1_1?crid=3NWEFCXZLJ19Z&keywords=Docker+Deep+Dive&qid=1671101038&s=books&sprefix=docker+deep+div%2Cstripbooks%2C158&sr=1-1',
   'https://www.amazon.com/Docker-Deep-Dive-Nigel-Poulton-ebook/dp/B01LXWQUFF/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1671101038&sr=1-1',
   'https://leanpub.com/dockerdeepdive',
   'https://i0.wp.com/nigelpoulton.com/wp-content/uploads/2023/01/DockerDeepDive3d.png?resize=315%2C371&amp;ssl=1',
   ''
),
(
   'Quick Start Kubernetes',
   'Quick Start Kubernetes assumes zero prior experience and gets you up-to-speed with Kubernetes fast!',
   'In less than 100 pages you’ll learn how Kubernetes works and deploy and manage a simple app.',
   'This book is perfect for anyone getting started or who would like a refresher on the basics of Kubernetes.',
   'Nigel Poulton',
   NULL,
   NULL,
   'https://www.amazon.com/Quick-Start-Kubernetes-Nigel-Poulton/dp/B09QFM8FWJ/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1671102575&sr=1-1',
   'https://www.amazon.com/Quick-Start-Kubernetes-Nigel-Poulton-ebook/dp/B08T21NW4Z/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1671102575&sr=1-1',
   'https://leanpub.com/quickstartkubernetes',
   'https://i0.wp.com/nigelpoulton.com/wp-content/uploads/2023/01/QSK_3D_2023.png?resize=315%2C371&amp;ssl=1',
   ''
),
(
   'THE KCNA BOOK',
   'If you want to smash the Kubernetes and Cloud Native Associate (KCNA) exam, this is the book for you!',
   'The KCNA Book covers every exam objective, in one place, in a well-organised and concise format. It contains over 200 chapter-review questions, as well as a full 60-question sample exam.',
   'When you’ve finished the book, you’ll be ready to smash the KCNA exam!',
   'Nigel Poulton',
   NULL,
   'https://www.amazon.com/Audible-The-KCNA-Book/dp/B09WVPKRYB/ref=tmm_aud_swatch_0?_encoding=UTF8&qid=1671102702&sr=1-1',
   'https://www.amazon.com/KCNA-Book-Kubernetes-Native-Associate/dp/B09SNKVG5M/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1671102702&sr=1-1',
   'https://www.amazon.com/KCNA-Book-Kubernetes-Native-Associate-ebook/dp/B09SQ4R2TM/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=1671102702&sr=1-1',
   'https://leanpub.com/thekcnabook',
   'https://i0.wp.com/nigelpoulton.com/wp-content/uploads/2022/11/KCNA_3D-e1668528670334.png?resize=315%2C371&amp;ssl=1',
   'Nigels latest book'
);
